name: Build
cmd: cargo build --release
sh: true
targets:
  format:
    sh:  true
    cmd: cargo fmt
    keymap: alt-cmd-f
  run:
    sh:  true
    cmd: cargo run --bin main --release
    keymap: alt-cmd-r
